/**
 * File: auto-update.nix
 * Author: ziyun
 * Date: 2026-09-10
 * Description: 定时自动检查并升级 packages/custom 下的自定义包。
 *
 * systemd timer 每日运行 update.sh --bump --all --verify：
 *   - 探测上游最新版本 → 预取 hash → 改 derivation
 *   - --verify：每个包 bump 后跑 nix build 验证，失败则 git checkout 回退
 *   - 全部通过后自动 git commit + push
 *   - 下次 nixos-rebuild 自然拿到新版本
 *
 * 手动触发：systemctl start flake-auto-update
 * 查看日志：journalctl -u flake-auto-update
 */
{ config, lib, pkgs, ... }:
let
  cfg = config.services.flake-auto-update;
  repoPath = "/home/ziyun/Documents/GitHub/ZiYyun-NixOSConfiguration";
in
{
  options.services.flake-auto-update = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;  # 默认所有主机启用；单台可设 false 关闭
      description = "定时自动升级 custom packages";
    };

    onCalendar = lib.mkOption {
      type = lib.types.str;
      default = "daily";
      description = "systemd OnCalendar 表达式（默认每天一次）";
    };

    autoPush = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "是否自动 git push（需代理已配置）";
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.services.flake-auto-update = {
      description = "Check and bump custom packages from upstream";
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];

      serviceConfig = {
        Type = "oneshot";
        User = "ziyun";
        Group = "users";
        WorkingDirectory = repoPath;
        # nix 需要 PATH 里的 nix、git 需要 HOME 里的配置（含代理）
        Environment = [
          "HOME=/home/ziyun"
          "PATH=/run/wrappers/bin:/home/ziyun/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/bin"
        ];
      };

      # update.sh --bump --all --verify 已在末尾 git add；
      # 此处检查是否有暂存改动，有则 commit + push
      script = ''
        ${repoPath}/packages/custom/update.sh --bump --all --verify || true

        if git diff --cached --quiet; then
          echo "[auto-update] 无更新"
        else
          git commit -m "chore: auto-bump custom packages

Generated by flake-auto-update systemd service.
$(date '+%F %T')"
          ${lib.optionalString cfg.autoPush ''
            git push origin main || echo "[auto-update] push 失败（可能代理未开），下次手动 push"
          ''}
        fi
      '';
    };

    systemd.timers.flake-auto-update = {
      description = "Daily check for custom package updates";
      timerConfig = {
        OnCalendar = cfg.onCalendar;
        Persistent = true;  # 错过的执行在开机后补跑
      };
      wantedBy = [ "timers.target" ];
    };
  };
}
